let colorMode = 'hsv'; // 'hsv' | 'grayscale' | 'viridis' | 'magma'
let intervalId = null;
let camWidth = 640;
let camHeight = 480;
let levels = 3;
let windowSize = 15;
let video = document.getElementById('webcam');
let showOriginal = false;
let canvas = document.getElementById('output');
let ctx = canvas.getContext('2d', { willReadFrequently: true });
let prevFrame = null;
let referenceFrame = null;
let contrastStrength = 3;

// Custom "Slider" resolution mode — instead of forcing an exact width+height
// (which distorts/stretches on devices whose natural camera aspect ratio
// doesn't match), this only requests a target HEIGHT from the camera and
// lets the browser pick the natural width for that height — avoiding stretch.
let useAutoResolution = false;
const RESOLUTION_STEPS = [360, 480, 720, 1080]; // heights only; width auto
let targetHeight = 720;

// Algorithm selector — 'opticalflow' (Farneback, has direction) or
// 'cfs' (Consecutive Frame Subtraction — Pocket Schlieren's fast, live-mode
// technique: simple absolute difference between frames, no direction info).
let algorithmMode = 'opticalflow';

// Blur applied before CFS's frame subtraction, to smooth out sensor noise/
// fringes (rolling shutter, AC light flicker) that raw pixel-diff exposes.
// Only used in CFS mode — Optical Flow already has implicit smoothing built
// into its calculation. Must be an odd number (OpenCV requirement).
let blurStrength = 3;

// Gamma correction — brightens (gamma>1) or darkens (gamma<1) the flow
// visualization without clipping extremes. Matches Pocket Schlieren's
// live-mode gamma correction. LUT (lookup table) precomputed for speed —
// rebuilt only when slider changes, not every frame.
let gammaValue = 1.0;
function buildGammaLUT(gamma) {
  let lut = new Float32Array(256);
  for (let i = 0; i < 256; i++) {
    lut[i] = 255 * Math.pow(i / 255, 1 / gamma);
  }
  return lut;
}
let gammaLUT = buildGammaLUT(gammaValue);

// Stores the last uploaded reference and flow images as data URLs so the
// Export Report button can embed them in the HTML report after processing.
let uploadRefDataUrl = null;
let uploadFlowDataUrl = null;

// Builds a descriptive filename tag from the current visualization settings,
// e.g. "bos_result_opticalflow_viridis_c3_g1_histeqON_l3_w15.png" — used for
// upload, burst, and recording downloads so exported files are self-documenting.
function buildResultFilename(extension) {
  let histTag = useHistEq ? 'histeqON' : 'histeqOFF';
  return 'bos_result_' + algorithmMode + '_' + colorMode + '_c' + contrastStrength + '_g' + gammaValue + '_' + histTag + '_l' + levels + '_w' + windowSize + '.' + extension;
}

// Generates a self-contained HTML experiment report and triggers a download.
// Embeds all three images (reference, flow, result) as base64 data URLs so
// the file is portable — no external dependencies, opens in any browser.
// Called from both the Upload and Burst Export Report buttons.
function exportReport(img1DataUrl, img2DataUrl, resultDataUrl) {
  let now = new Date();
  let dateStr = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
  let timeStr = now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
  let histEqStatus = useHistEq ? 'ON' : 'OFF';

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>BOS Experiment Report</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 900px; margin: 40px auto; padding: 20px; color: #222; }
    h1 { color: #0055aa; border-bottom: 2px solid #0055aa; padding-bottom: 10px; }
    h2 { color: #0055aa; margin-top: 30px; }
    table { border-collapse: collapse; width: 100%; max-width: 400px; margin-bottom: 20px; }
    td { padding: 8px 14px; border: 1px solid #ccc; }
    td:first-child { font-weight: bold; background: #f0f4ff; width: 50%; }
    .images { display: flex; gap: 20px; flex-wrap: wrap; margin-top: 10px; }
    .img-box { text-align: center; }
    .img-box img { max-width: 260px; border: 2px solid #0055aa; border-radius: 6px; }
    .img-box p { margin: 6px 0 0; font-weight: bold; color: #0055aa; }
    .footer { margin-top: 40px; font-size: 12px; color: #888; border-top: 1px solid #ccc; padding-top: 10px; }
  </style>
</head>
<body>
  <h1>Generated by WEB BOS App  — IIT Delhi SeNSE</h1>
  <p><strong>Date:</strong> ${dateStr}</p>
  <p><strong>Time:</strong> ${timeStr}</p>

  <h2>Settings</h2>
  <table>
    <tr><td>Resolution</td><td>${camWidth}x${camHeight}</td></tr>
    <tr><td>Algorithm</td><td>${algorithmMode}</td></tr>
    <tr><td>Colormap</td><td>${colorMode}</td></tr>
    <tr><td>Contrast Strength</td><td>${contrastStrength}</td></tr>
    <tr><td>Gamma</td><td>${gammaValue}</td></tr>
    <tr><td>Levels</td><td>${levels}</td></tr>
    <tr><td>Window Size</td><td>${windowSize}</td></tr>
    <tr><td>Histogram Equalization</td><td>${histEqStatus}</td></tr>
  </table>

  <h2>Images</h2>
  <div class="images">
    <div class="img-box">
      <img src="${img1DataUrl}" alt="Reference Image">
      <p>Reference Image</p>
    </div>
    <div class="img-box">
      <img src="${img2DataUrl}" alt="Flow Image">
      <p>Flow Image</p>
    </div>
    <div class="img-box">
      <img src="${resultDataUrl}" alt="BOS Result">
      <p>BOS Result</p>
    </div>
  </div>

  <div class="footer">Generated by BOS WEB BOS App — IIT Delhi SeNSE</div>
</body>
</html>`;

  let blob = new Blob([html], { type: 'text/html' });
  let url = URL.createObjectURL(blob);
  let link = document.createElement('a');
  link.download = 'bos_report_' + now.getFullYear() + '_' + (now.getMonth()+1) + '_' + now.getDate() + '_' + now.getHours() + now.getMinutes() + '.html';
  link.href = url;
  link.click();
}

function exportReportJSON(refFilename, flowFilename, resultFilename) {
  let now = new Date();
  let reportData = {
    timestamp: now.toISOString(),
    settings: {
      resolution: camWidth + 'x' + camHeight,
      algorithm: algorithmMode,
      colormap: colorMode,
      contrastStrength: contrastStrength,
      gamma: gammaValue,
      levels: levels,
      windowSize: windowSize,
      histogramEqualization: useHistEq
    },
    imageFiles: {
      reference: refFilename,
      flow: flowFilename,
      result: resultFilename
    }
  };

  let blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
  let url = URL.createObjectURL(blob);
  let link = document.createElement('a');
  link.download = 'bos_report_' + now.getFullYear() + '_' + (now.getMonth()+1) + '_' + now.getDate() + '_' + now.getHours() + now.getMinutes() + '.json';
  link.href = url;
  link.click();
}

// ROI variables
let roi = null; // {x, y, w, h}
let isDrawing = false;
let startX = 0;
let startY = 0;

let frameCount = 0;
let lastTime = performance.now();

document.getElementById('captureBtn').addEventListener('click', function() {
  if (referenceFrame == null) {
    referenceFrame = prevFrame;
    this.innerText = "Reference Frame Captured ✅ (Click to reset)";
  } else {
    referenceFrame = null;
    this.innerText = "Capture Reference Frame";
  }
});

document.getElementById('viewToggleBtn').addEventListener('click', function() {
  showOriginal = !showOriginal;
  if (showOriginal) {
    video.style.display = 'block';
    canvas.style.display = 'none';
    this.innerText = '🔄 Show BOS Feed';
  } else {
    video.style.display = 'none';
    canvas.style.display = 'block';
    this.innerText = '🔄 Show Original Feed';
  }
});

document.getElementById('colorModeSelect').addEventListener('change', function() {
  colorMode = this.value; // 'hsv' | 'grayscale' | 'viridis' | 'magma'
});

document.getElementById('algorithmSelect').addEventListener('change', function() {
  algorithmMode = this.value; // 'opticalflow' | 'cfs'
  updateAlgorithmUI();
});

// Greys out sliders that have no effect for the currently selected algorithm
// (Levels/Window are Optical Flow-only; Blur is CFS-only), so the UI doesn't
// invite adjusting a control that won't do anything.
function updateAlgorithmUI() {
  let levelsGroup = document.getElementById('levelsSlider').closest('.slider-group');
  let windowGroup = document.getElementById('windowSlider').closest('.slider-group');
  let blurGroup = document.getElementById('blurSlider').closest('.slider-group');

  if (algorithmMode === 'cfs') {
    document.getElementById('levelsSlider').disabled = true;
    document.getElementById('windowSlider').disabled = true;
    document.getElementById('blurSlider').disabled = false;
    levelsGroup.classList.add('slider-disabled');
    windowGroup.classList.add('slider-disabled');
    blurGroup.classList.remove('slider-disabled');
  } else {
    document.getElementById('levelsSlider').disabled = false;
    document.getElementById('windowSlider').disabled = false;
    document.getElementById('blurSlider').disabled = true;
    levelsGroup.classList.remove('slider-disabled');
    windowGroup.classList.remove('slider-disabled');
    blurGroup.classList.add('slider-disabled');
  }
}

// Set the correct initial state on page load (default algorithm is Optical Flow)
updateAlgorithmUI();

document.getElementById('blurSlider').addEventListener('input', function() {
  let val = parseInt(this.value);
  if (val % 2 === 0) val += 1;  // force odd (OpenCV kernel size requirement)
  blurStrength = val;
  document.getElementById('blurVal').innerText = val;
});

let useHistEq = false;
document.getElementById('histEqCheckbox').addEventListener('change', function() {
  useHistEq = this.checked;
});

// ROI drawing on canvas
canvas.addEventListener('mousedown', function(e) {
  let rect = canvas.getBoundingClientRect();
  let scaleX = camWidth / rect.width;
  let scaleY = camHeight / rect.height;
  startX = (e.clientX - rect.left) * scaleX;
  startY = (e.clientY - rect.top) * scaleY;
  isDrawing = true;
  roi = null;
});

canvas.addEventListener('mousemove', function(e) {
  if (!isDrawing) return;
  let rect = canvas.getBoundingClientRect();
  let scaleX = camWidth / rect.width;
  let scaleY = camHeight / rect.height;
  let currentX = (e.clientX - rect.left) * scaleX;
  let currentY = (e.clientY - rect.top) * scaleY;
  roi = clampRoi({
    x: Math.min(startX, currentX),
    y: Math.min(startY, currentY),
    w: Math.abs(currentX - startX),
    h: Math.abs(currentY - startY)
  });
});

canvas.addEventListener('mouseup', function() {
  isDrawing = false;
  if (roi && (roi.w < 20 || roi.h < 20)) {
    roi = null;
  }
});

// Touch support for mobile
canvas.addEventListener('touchstart', function(e) {
  e.preventDefault();
  let rect = canvas.getBoundingClientRect();
  let scaleX = camWidth / rect.width;
  let scaleY = camHeight / rect.height;
  let touch = e.touches[0];
  startX = (touch.clientX - rect.left) * scaleX;
  startY = (touch.clientY - rect.top) * scaleY;
  isDrawing = true;
  roi = null;
});

canvas.addEventListener('touchmove', function(e) {
  e.preventDefault();
  if (!isDrawing) return;
  let rect = canvas.getBoundingClientRect();
  let scaleX = camWidth / rect.width;
  let scaleY = camHeight / rect.height;
  let touch = e.touches[0];
  let currentX = (touch.clientX - rect.left) * scaleX;
  let currentY = (touch.clientY - rect.top) * scaleY;
  roi = clampRoi({
    x: Math.min(startX, currentX),
    y: Math.min(startY, currentY),
    w: Math.abs(currentX - startX),
    h: Math.abs(currentY - startY)
  });
});

canvas.addEventListener('touchend', function() {
  isDrawing = false;
  if (roi && (roi.w < 20 || roi.h < 20)) {
    roi = null;
  }
});

// Keeps the ROI box fully inside the current frame bounds so cv.Mat.roi()
// never receives an out-of-bounds rect (which throws an OpenCV assertion error)
function clampRoi(r) {
  let x = Math.max(0, Math.min(r.x, camWidth - 1));
  let y = Math.max(0, Math.min(r.y, camHeight - 1));
  let w = Math.min(r.w, camWidth - x);
  let h = Math.min(r.h, camHeight - y);
  return { x, y, w, h };
}

let isPaused = false;

let currentCamera = 'user'; // user = front, environment = back

document.getElementById('switchBtn').addEventListener('click', function() {
  if (currentCamera === 'user') {
    currentCamera = 'environment';
    this.innerText = '🤳 Switch to Front Camera';
  } else {
    currentCamera = 'user';
    this.innerText = '📷 Switch to Back Camera';
  }
  prevFrame = null;
  referenceFrame = null;
  startWebcam();
});

let flashOn = false;

document.getElementById('flashBtn').addEventListener('click', async function() {
  let track = video.srcObject && video.srcObject.getVideoTracks()[0];
  if (!track) {
    alert('Camera not available!');
    return;
  }
  let capabilities = track.getCapabilities();
  if (!capabilities.torch) {
    alert('Flash not supported on this device/camera!');
    return;
  }
  flashOn = !flashOn;
  await track.applyConstraints({
    advanced: [{ torch: flashOn }]
  });
  this.innerText = flashOn ? '🔦 Flash ON' : '🔦 Flash OFF';
});

document.getElementById('pauseBtn').addEventListener('click', function() {
  if (!isPaused) {
    if (intervalId) {
      clearInterval(intervalId);
      intervalId = null;
    }
    if (video.srcObject) {
      video.srcObject.getTracks().forEach(track => track.stop());
    }
    isPaused = true;
    this.innerText = "▶️ Resume Feed";
  } else {
    isPaused = false;
    this.innerText = "⏸️ Pause Feed";
    startWebcam();
  }
});

document.getElementById('contrastSlider').addEventListener('input', function() {
  contrastStrength = parseFloat(this.value);
  document.getElementById('contrastVal').innerText = this.value;
});

document.getElementById('gammaSlider').addEventListener('input', function() {
  gammaValue = parseFloat(this.value);
  document.getElementById('gammaVal').innerText = this.value;
  gammaLUT = buildGammaLUT(gammaValue);
});

document.getElementById('levelsSlider').addEventListener('input', function() {
  levels = parseInt(this.value);
  document.getElementById('levelsVal').innerText = this.value;
});

document.getElementById('windowSlider').addEventListener('input', function() {
  windowSize = parseInt(this.value);
  document.getElementById('windowVal').innerText = this.value;
});

document.getElementById('resSelect').addEventListener('change', function() {
  if (this.value === 'slider') {
    // Switch to auto-aspect-ratio mode — show the quality slider, hide
    // the fixed-resolution behaviour. Actual camWidth/camHeight will be
    // set later from the real video stream dimensions (natural ratio).
    useAutoResolution = true;
    document.getElementById('resSliderGroup').style.display = 'block';
    document.getElementById('resVal').innerText = 'Auto';

    targetHeight = RESOLUTION_STEPS[document.getElementById('resSlider').value];
    document.getElementById('resSliderVal').innerText = targetHeight + 'p';
  } else {
    // Back to fixed width x height mode (old behaviour)
    useAutoResolution = false;
    document.getElementById('resSliderGroup').style.display = 'none';

    let parts = this.value.split('x');
    camWidth = parseInt(parts[0]);
    camHeight = parseInt(parts[1]);
    document.getElementById('resVal').innerText = this.value;
    canvas.width = camWidth;
    canvas.height = camHeight;
    video.width = camWidth;
    video.height = camHeight;
  }

  prevFrame = null;
  referenceFrame = null;
  roi = null;
  document.getElementById('captureBtn').innerText = "Capture Reference Frame";
  startWebcam();
});

// Quality slider (360p/480p/720p/1080p) — only active when resSelect is
// set to 'slider' mode. Only requests height from the camera; width is
// left to the browser's natural aspect ratio for that device.
document.getElementById('resSlider').addEventListener('input', function() {
  targetHeight = RESOLUTION_STEPS[parseInt(this.value)];
  document.getElementById('resSliderVal').innerText = targetHeight + 'p';

  prevFrame = null;
  referenceFrame = null;
  roi = null;
  document.getElementById('captureBtn').innerText = "Capture Reference Frame";
  startWebcam();
});

document.getElementById('processBtn').addEventListener('click', function() {
  let refFile = document.getElementById('refImage').files[0];
  let flowFile = document.getElementById('flowImage').files[0];
  if (!refFile || !flowFile) {
    alert('Please select both images!');
    return;
  }
  if (refFile.size > 2 * 1024 * 1024 || flowFile.size > 2 * 1024 * 1024) {
    alert('Warning: Image size is over 2MB. This may slow down processing or crash on mobile.');
  }

  // Convert both files to base64 first so they can be embedded in the
  // HTML report — URL.createObjectURL() URLs expire after the session ends
  let reader1 = new FileReader();
  let reader2 = new FileReader();

  reader1.onload = function(e1) {
    uploadRefDataUrl = e1.target.result;
    reader2.onload = function(e2) {
      uploadFlowDataUrl = e2.target.result;

  let img1 = new Image();
  let img2 = new Image();

  img1.onload = function() {
    img2.onload = function() {
      if (img1.width !== img2.width || img1.height !== img2.height) {
        alert('Warning: Both images have different resolutions!\nImage 1: ' + img1.width + 'x' + img1.height + '\nImage 2: ' + img2.width + 'x' + img2.height + '\nResults may be incorrect!');
      }

      canvas.width = img1.width;
      canvas.height = img1.height;

      ctx.drawImage(img1, 0, 0);
      let frame1 = ctx.getImageData(0, 0, img1.width, img1.height);
      ctx.drawImage(img2, 0, 0);
      let frame2 = ctx.getImageData(0, 0, img2.width, img2.height);

      let mat1 = cv.matFromImageData(frame1);
      let mat2 = cv.matFromImageData(frame2);
      let gray1 = new cv.Mat();
      let gray2 = new cv.Mat();
      cv.cvtColor(mat1, gray1, cv.COLOR_RGBA2GRAY);
      cv.cvtColor(mat2, gray2, cv.COLOR_RGBA2GRAY);

      let uploadResult = computeMagnitudeAngle(gray1, gray2);

      visualizeFlow(uploadResult.magnitude, uploadResult.angle);

      // Store images for export report — kept as data URLs so they can be
      // embedded directly in the HTML report without needing external files
      uploadRefDataUrl = img1.src;
      uploadFlowDataUrl = img2.src;

      document.getElementById('downloadBtn').style.display = 'inline-block';
      document.getElementById('exportReportUploadBtn').style.display = 'inline-block';
      document.getElementById('exportJsonUploadBtn').style.display = 'inline-block';
      if (intervalId) {
        clearInterval(intervalId);
        intervalId = null;
      }
      document.getElementById('resumeBtn').style.display = 'inline-block';

      mat1.delete(); mat2.delete();
      gray1.delete(); gray2.delete();
      uploadResult.magnitude.delete();
      if (uploadResult.angle) uploadResult.angle.delete();
    };
    img2.src = uploadFlowDataUrl;
  };
  img1.src = uploadRefDataUrl;

    }; // reader2.onload end
    reader2.readAsDataURL(flowFile);
  }; // reader1.onload end
  reader1.readAsDataURL(refFile);
});

document.getElementById('downloadBtn').addEventListener('click', function() {
  let link = document.createElement('a');
  link.download = buildResultFilename('png');
  link.href = canvas.toDataURL();
  link.click();
});

document.getElementById('exportReportUploadBtn').addEventListener('click', function() {
  exportReport(uploadRefDataUrl, uploadFlowDataUrl, canvas.toDataURL());
});
document.getElementById('exportJsonUploadBtn').addEventListener('click', function() {
  exportReportJSON('uploaded_reference.png', 'uploaded_flow.png', buildResultFilename('png'));
});
document.getElementById('resumeBtn').addEventListener('click', function() {
  document.getElementById('resumeBtn').style.display = 'none';
  document.getElementById('downloadBtn').style.display = 'none';
  document.getElementById('exportReportUploadBtn').style.display = 'none';
  document.getElementById('exportJsonUploadBtn').style.display = 'none';
  captureFrames();
});

let burstImg1 = null;
let burstImg2 = null;

document.getElementById('burstBtn').addEventListener('click', function() {
  this.innerText = "Capturing...";
  this.disabled = true;

  // If an ROI is selected, capture only that cropped region — source-crop
  // straight from the video feed (sx, sy, sw, sh) so the temp canvas itself
  // is ROI-sized, not the full frame. Otherwise fall back to full frame.
  let useRoi = roi && roi.w > 20 && roi.h > 20;
  let captureX = useRoi ? Math.floor(roi.x) : 0;
  let captureY = useRoi ? Math.floor(roi.y) : 0;
  let captureW = useRoi ? Math.floor(roi.w) : camWidth;
  let captureH = useRoi ? Math.floor(roi.h) : camHeight;

  let tempCanvas = document.createElement('canvas');
  tempCanvas.width = captureW;
  tempCanvas.height = captureH;
  let tempCtx = tempCanvas.getContext('2d');
  tempCtx.drawImage(video, captureX, captureY, captureW, captureH, 0, 0, captureW, captureH);
  burstImg1 = tempCanvas.toDataURL('image/png');

  setTimeout(function() {
    tempCtx.drawImage(video, captureX, captureY, captureW, captureH, 0, 0, captureW, captureH);
    burstImg2 = tempCanvas.toDataURL('image/png');

    let img1 = new Image();
    let img2 = new Image();

    img1.onload = function() {
      img2.onload = function() {
        canvas.width = captureW;
        canvas.height = captureH;

        ctx.drawImage(img1, 0, 0);
        let frame1 = ctx.getImageData(0, 0, captureW, captureH);
        ctx.drawImage(img2, 0, 0);
        let frame2 = ctx.getImageData(0, 0, captureW, captureH);

        let mat1 = cv.matFromImageData(frame1);
        let mat2 = cv.matFromImageData(frame2);
        let gray1 = new cv.Mat();
        let gray2 = new cv.Mat();
        cv.cvtColor(mat1, gray1, cv.COLOR_RGBA2GRAY);
        cv.cvtColor(mat2, gray2, cv.COLOR_RGBA2GRAY);

        let burstResult = computeMagnitudeAngle(gray1, gray2);

        visualizeFlow(burstResult.magnitude, burstResult.angle);

        document.getElementById('burstDownloads').style.display = 'flex';
        document.getElementById('exportReportBurstBtn').style.display = 'inline-block';
        document.getElementById('exportJsonBurstBtn').style.display = 'inline-block';
        document.getElementById('burstBtn').innerText = "📸 Capture Burst";
        document.getElementById('burstBtn').disabled = false;

        if (intervalId) {
  clearInterval(intervalId);
  intervalId = null;
}
document.getElementById('resumeBurstBtn').style.display = 'inline-block';

        mat1.delete(); mat2.delete();
        gray1.delete(); gray2.delete();
        burstResult.magnitude.delete();
        if (burstResult.angle) burstResult.angle.delete();
      };
      img2.src = burstImg2;
    };
    img1.src = burstImg1;
  }, 0);
});

document.getElementById('downloadImg1').addEventListener('click', function() {
  let link = document.createElement('a');
  link.download = 'burst_image1.png';
  link.href = burstImg1;
  link.click();
});

document.getElementById('downloadImg2').addEventListener('click', function() {
  let link = document.createElement('a');
  link.download = 'burst_image2.png';
  link.href = burstImg2;
  link.click();
});

document.getElementById('downloadFlow').addEventListener('click', function() {
  let link = document.createElement('a');
  link.download = buildResultFilename('png');
  link.href = canvas.toDataURL();
  link.click();
});

document.getElementById('exportReportBurstBtn').addEventListener('click', function() {
  exportReport(burstImg1, burstImg2, canvas.toDataURL());
});

document.getElementById('exportJsonBurstBtn').addEventListener('click', function() {
  exportReportJSON('burst_image1.png', 'burst_image2.png', buildResultFilename('png'));
});

document.getElementById('resumeBurstBtn').addEventListener('click', function() {
  document.getElementById('resumeBurstBtn').style.display = 'none';
  document.getElementById('burstDownloads').style.display = 'none';
  document.getElementById('exportReportBurstBtn').style.display = 'none';
  document.getElementById('exportJsonBurstBtn').style.display = 'none';

  // Reset canvas back to full default size — burst may have shrunk it
  // to ROI dimensions for cropped capture/computation.
  canvas.width = camWidth;
  canvas.height = camHeight;

  captureFrames();
});

let mediaRecorder = null;
let recordedChunks = [];
let recordingTimer = null;
let recordingSeconds = 0;

// Recording-specific ROI crop support — frozen at the moment recording
// starts (changing ROI mid-recording cannot resize an in-progress video,
// so we lock it in and ignore further ROI changes until recording stops).
let isRecording = false;
let recordRoi = null;      // null = full frame, else {x,y,w,h} fixed at start
let recordCanvas = null;
let recordCtx = null;

document.getElementById('recordBtn').addEventListener('click', function() {
  if (mediaRecorder && mediaRecorder.state === 'recording') {
    mediaRecorder.stop();
    clearInterval(recordingTimer);
    isRecording = false;
    this.innerText = '🔴 Start Recording';
    document.getElementById('recordTimer').innerText = '00:00';
  } else {
    if (camWidth > 320) {
      alert('Warning: High resolution may cause lag or crash during recording. Recommended: 320x240 or lower.');
    }
    recordedChunks = [];
    recordingSeconds = 0;
    document.getElementById('downloadRecordBtn').style.display = 'none';

    // Freeze the current ROI (if any) for the entire recording duration.
    recordRoi = (roi && roi.w > 20 && roi.h > 20) ? { x: roi.x, y: roi.y, w: roi.w, h: roi.h } : null;

    let recWidth = recordRoi ? Math.floor(recordRoi.w) : camWidth;
    let recHeight = recordRoi ? Math.floor(recordRoi.h) : camHeight;

    recordCanvas = document.createElement('canvas');
    recordCanvas.width = recWidth;
    recordCanvas.height = recHeight;
    recordCtx = recordCanvas.getContext('2d');

    isRecording = true;

    let stream = recordCanvas.captureStream();
    mediaRecorder = new MediaRecorder(stream, {
  mimeType: 'video/webm',
  videoBitsPerSecond: 8000000  // 8 Mbps — higher = better quality, bigger file
});

    mediaRecorder.ondataavailable = function(e) {
      if (e.data.size > 0) recordedChunks.push(e.data);
    };

    mediaRecorder.onstop = function() {
      let blob = new Blob(recordedChunks, { type: 'video/webm' });
      let url = URL.createObjectURL(blob);
      let downloadBtn = document.getElementById('downloadRecordBtn');
      downloadBtn.style.display = 'inline-block';
      downloadBtn.onclick = function() {
        let link = document.createElement('a');
        link.download = buildResultFilename('webm');
        link.href = url;
        link.click();
      };
    };

    mediaRecorder.start();
    this.innerText = '⏹️ Stop Recording';

    recordingTimer = setInterval(function() {
      recordingSeconds++;
      let mins = Math.floor(recordingSeconds / 60).toString().padStart(2, '0');
      let secs = (recordingSeconds % 60).toString().padStart(2, '0');
      document.getElementById('recordTimer').innerText = mins + ':' + secs;
      if (recordingSeconds >= 30) {
        mediaRecorder.stop();
        clearInterval(recordingTimer);
        isRecording = false;
        document.getElementById('recordBtn').innerText = '🔴 Start Recording';
        document.getElementById('recordTimer').innerText = '00:00';
      }
    }, 1000);
  }
});

function onOpenCvReady() {
  console.log("OpenCV Ready!");
  startWebcam();
}

function startWebcam() {
  if (video.srcObject) {
    video.srcObject.getTracks().forEach(track => track.stop());
  }

  // In auto-resolution ("slider") mode, only request a target height —
  // no width constraint at all — so the browser picks the device's own
  // natural width for that height, avoiding the stretch/distortion that
  // happens when forcing an exact width+height combo the camera doesn't
  // natively support.
  let videoConstraints = useAutoResolution
    ? { facingMode: { exact: currentCamera }, height: { ideal: targetHeight } }
    : { facingMode: { exact: currentCamera }, width: camWidth, height: camHeight };

  let constraints = { video: videoConstraints };

  navigator.mediaDevices.getUserMedia(constraints)
    .then(function(stream) {
      video.srcObject = stream;
      console.log("Webcam working! Camera: " + currentCamera);

      // Once the stream's real dimensions are known, sync canvas/camWidth/
      // camHeight to them — critical in auto mode where we didn't dictate
      // width, but harmless (a no-op) in fixed mode too.
      video.onloadedmetadata = function() {
        if (useAutoResolution) {
          camWidth = video.videoWidth;
          camHeight = video.videoHeight;
          canvas.width = camWidth;
          canvas.height = camHeight;
          video.width = camWidth;
          video.height = camHeight;
        }
      };

      setTimeout(captureFrames, 1000);
    })
    .catch(function(error) {
      console.log("Camera switch error: " + error);
      let fallbackConstraints = useAutoResolution
        ? { facingMode: currentCamera, height: { ideal: targetHeight } }
        : { facingMode: currentCamera, width: camWidth, height: camHeight };

      navigator.mediaDevices.getUserMedia({ video: fallbackConstraints })
      .then(function(stream) {
        video.srcObject = stream;
        console.log("Webcam working fallback!");

        video.onloadedmetadata = function() {
          if (useAutoResolution) {
            camWidth = video.videoWidth;
            camHeight = video.videoHeight;
            canvas.width = camWidth;
            canvas.height = camHeight;
            video.width = camWidth;
            video.height = camHeight;
          }
        };

        setTimeout(captureFrames, 1000);
      })
      .catch(function(err) {
        console.log("Webcam error: " + err);
      });
    });
}

function captureFrames() {
  if (intervalId) clearInterval(intervalId);

  intervalId = setInterval(function() {
    ctx.drawImage(video, 0, 0, camWidth, camHeight);
    let currentFrame = ctx.getImageData(0, 0, camWidth, camHeight);

    let baseFrame = referenceFrame != null ? referenceFrame : prevFrame;

    if (baseFrame != null) {
      let prev = cv.matFromImageData(baseFrame);
      let curr = cv.matFromImageData(currentFrame);

      let prevGray = new cv.Mat();
      let currGray = new cv.Mat();
      cv.cvtColor(prev, prevGray, cv.COLOR_RGBA2GRAY);
      cv.cvtColor(curr, currGray, cv.COLOR_RGBA2GRAY);

      // ROI — To process only selected area
      if (roi && roi.w > 20 && roi.h > 20) {
        let roiRect = new cv.Rect(
          Math.floor(roi.x), Math.floor(roi.y),
          Math.floor(roi.w), Math.floor(roi.h)
        );

        let prevRoi = prevGray.roi(roiRect);
        let currRoi = currGray.roi(roiRect);

        let roiResult = computeMagnitudeAngle(prevRoi, currRoi);

        // Only show flow on ROI area, black canvas elsewhere
        ctx.fillStyle = 'black';
        ctx.fillRect(0, 0, camWidth, camHeight);

        // Draw ROI box outline
        ctx.strokeStyle = '#00e5ff';
        ctx.lineWidth = 2;
        ctx.strokeRect(roi.x, roi.y, roi.w, roi.h);

        visualizeFlowInROI(roiResult.magnitude, roiResult.angle, roi);
        updateFPS();

        prevRoi.delete();
        currRoi.delete();
        roiResult.magnitude.delete();
        if (roiResult.angle) roiResult.angle.delete();
      } else {
        // No ROI — process full frame
        let liveResult = computeMagnitudeAngle(prevGray, currGray);

        visualizeFlow(liveResult.magnitude, liveResult.angle);
        updateFPS();
        liveResult.magnitude.delete();
        if (liveResult.angle) liveResult.angle.delete();
      }

      prev.delete();
      curr.delete();
      prevGray.delete();
      currGray.delete();
    }

    // If recording is active, copy the frozen crop region from the main
    // canvas into the dedicated recording canvas — this is what actually
    // gets streamed/recorded, so it stays locked to the ROI size chosen
    // at recording start, regardless of any later ROI changes.
    if (isRecording && recordCanvas) {
      if (recordRoi) {
        recordCtx.drawImage(
          canvas,
          Math.floor(recordRoi.x), Math.floor(recordRoi.y),
          Math.floor(recordRoi.w), Math.floor(recordRoi.h),
          0, 0,
          recordCanvas.width, recordCanvas.height
        );
      } else {
        recordCtx.drawImage(canvas, 0, 0, camWidth, camHeight, 0, 0, recordCanvas.width, recordCanvas.height);
      }
    }

    prevFrame = currentFrame;
  }, 20);
}

function updateFPS() {
  frameCount++;
  let now = performance.now();
  let elapsed = now - lastTime;
  if (elapsed >= 1000) {
    let fps = Math.round((frameCount * 1000) / elapsed);
    document.getElementById('fps').innerText = "FPS: " + fps;
    frameCount = 0;
    lastTime = now;
  }
}

// Viridis and Magma colormaps implemented as manual RGB lookup tables,
// interpolated from standard matplotlib control-point colors. This avoids
// depending on cv.applyColorMap()/cv.COLORMAP_VIRIDIS/cv.COLORMAP_MAGMA,
// which are part of the colormap module and are NOT present in every
// opencv.js build — when missing, calling them throws before cv.imshow()
// ever runs, which is why the canvas was stuck showing the raw camera feed.
// cv.LUT() is a core function and is reliably available everywhere.
const VIRIDIS_STOPS = [
  [0.000, 68, 1, 84],
  [0.125, 72, 40, 120],
  [0.250, 62, 74, 137],
  [0.375, 49, 104, 142],
  [0.500, 38, 130, 142],
  [0.625, 31, 158, 137],
  [0.750, 53, 183, 121],
  [0.875, 109, 205, 89],
  [1.000, 253, 231, 37]
];

const MAGMA_STOPS = [
  [0.000, 0, 0, 4],
  [0.125, 28, 16, 68],
  [0.250, 79, 18, 123],
  [0.375, 129, 37, 129],
  [0.500, 181, 54, 122],
  [0.625, 229, 80, 100],
  [0.750, 251, 135, 97],
  [0.875, 254, 194, 135],
  [1.000, 252, 253, 191]
];

const INFERNO_STOPS = [
  [0.000, 0, 0, 4],
  [0.125, 27, 12, 66],
  [0.250, 75, 12, 107],
  [0.375, 120, 28, 109],
  [0.500, 165, 44, 96],
  [0.625, 207, 68, 70],
  [0.750, 237, 105, 37],
  [0.875, 251, 155, 6],
  [1.000, 252, 255, 164]
];

function buildColormapLUT(stops) {
  let lutData = new Uint8Array(256 * 3);
  for (let i = 0; i < 256; i++) {
    let t = i / 255;
    let idx = 0;
    while (idx < stops.length - 2 && stops[idx + 1][0] < t) idx++;
    let [t0, r0, g0, b0] = stops[idx];
    let [t1, r1, g1, b1] = stops[idx + 1];
    let localT = (t1 === t0) ? 0 : (t - t0) / (t1 - t0);
    lutData[i * 3 + 0] = Math.round(r0 + (r1 - r0) * localT);
    lutData[i * 3 + 1] = Math.round(g0 + (g1 - g0) * localT);
    lutData[i * 3 + 2] = Math.round(b0 + (b1 - b0) * localT);
  }
  return lutData;
}

// Plain JS arrays — built once at load time. No cv.Mat, no cv.LUT,
// no cv.applyColorMap. This is pure JavaScript with zero OpenCV
// dependency, so it works regardless of which opencv.js build is loaded.
const VIRIDIS_LUT = buildColormapLUT(VIRIDIS_STOPS);
const MAGMA_LUT = buildColormapLUT(MAGMA_STOPS);
const INFERNO_LUT = buildColormapLUT(INFERNO_STOPS);

function getColormapLUT(mode) {
  if (mode === 'viridis') return VIRIDIS_LUT;
  if (mode === 'inferno') return INFERNO_LUT;
  return MAGMA_LUT;
}

// Converts magNorm (CV_32F, 0-255) to an 8-bit Mat, applying histogram
// equalization if enabled. Caller must delete the returned Mat.
function toGray8(magNorm) {
  let gray8 = new cv.Mat();
  magNorm.convertTo(gray8, cv.CV_8U);
  if (useHistEq) {
    try {
      cv.equalizeHist(gray8, gray8);
    } catch (err) {
      console.error('Histogram equalization failed:', err);
    }
  }
  return gray8;
}

// Reads an 8-bit single-channel Mat's raw pixel data directly and paints it
// onto the given canvas context via a manual colormap lookup + putImageData.
// No OpenCV colormap/LUT function is used anywhere here.
function renderMagnitudeColormap(gray8, targetCtx, offsetX, offsetY) {
  let cols = gray8.cols;
  let rows = gray8.rows;
  let src = gray8.data;
  let lut = getColormapLUT(colorMode);

  let imgData = targetCtx.createImageData(cols, rows);
  let out = imgData.data;

  for (let i = 0, n = cols * rows; i < n; i++) {
    let lutIdx = src[i] * 3;
    let outIdx = i * 4;
    out[outIdx] = lut[lutIdx];
    out[outIdx + 1] = lut[lutIdx + 1];
    out[outIdx + 2] = lut[lutIdx + 2];
    out[outIdx + 3] = 255;
  }

  targetCtx.putImageData(imgData, offsetX || 0, offsetY || 0);
}

// Plain min-max normalization stretches 0-255 based on the single brightest
// and darkest pixel in the whole frame. A handful of outlier pixels (e.g.
// edge/misalignment artifacts between the two source frames) can dominate
// that range and crush the real, subtle signal down near black.
// This clips magnitude to (mean + contrastStrength*stddev) BEFORE normalizing,
// so a few extreme outliers no longer set the scale for the entire image.
// cv.meanStdDev / cv.threshold are core functions present in virtually
// every opencv.js build (unlike colormap/LUT), but this still falls back
// to plain normalize if something's missing, rather than crashing.
function normalizeMagnitudeRobust(magnitude, magNorm) {
  try {
    let meanMat = new cv.Mat();
    let stddevMat = new cv.Mat();
    cv.meanStdDev(magnitude, meanMat, stddevMat);
    let meanVal = meanMat.data64F[0];
    let stdVal = stddevMat.data64F[0];
    meanMat.delete();
    stddevMat.delete();

    let clipMax = meanVal + contrastStrength * stdVal;
    if (!isFinite(clipMax) || clipMax < 1e-6) {
      cv.normalize(magnitude, magNorm, 0, 255, cv.NORM_MINMAX);
      return;
    }

    let clipped = new cv.Mat();
    cv.threshold(magnitude, clipped, clipMax, clipMax, cv.THRESH_TRUNC);
    cv.normalize(clipped, magNorm, 0, 255, cv.NORM_MINMAX);
    clipped.delete();
  } catch (err) {
    console.error('Robust normalize failed, falling back to plain min-max:', err);
    cv.normalize(magnitude, magNorm, 0, 255, cv.NORM_MINMAX);
  }
}

// Applies the gamma LUT in-place to magNorm (CV_32F, values 0-255).
// Runs BEFORE the colormap branch (HSV/Grayscale/Viridis/Magma), so
// gamma affects all visualization modes identically. Skipped entirely
// when gamma = 1.0 (no-op) so default behaviour has zero extra cost.
function applyGammaCorrection(magNorm) {
  if (gammaValue === 1.0) return;
  let data = magNorm.data32F;
  for (let i = 0; i < data.length; i++) {
    let v = data[i];
    let idx = v < 0 ? 0 : (v > 255 ? 255 : Math.round(v));
    data[i] = gammaLUT[idx];
  }
}

// Computes magnitude (and angle, if available) for two grayscale frames,
// based on the selected algorithm:
// - 'opticalflow': Farneback — has direction (angle)
// - 'cfs': Consecutive Frame Subtraction (Pocket Schlieren's fast technique)
//   — simple absolute difference between frames, no direction info
//   (angle comes back null). Much cheaper to compute than Farneback.
// Caller must delete() the returned magnitude Mat, and angle too if not null.
function computeMagnitudeAngle(grayA, grayB) {
  if (algorithmMode === 'cfs') {
    // Blur BEFORE subtracting — smooths sensor noise/fringes so they don't
    // get exposed by the raw pixel-diff (see blurStrength comment above).
    let blurA = new cv.Mat();
    let blurB = new cv.Mat();
    let ksize = new cv.Size(blurStrength, blurStrength);
    cv.GaussianBlur(grayA, blurA, ksize, 0, 0, cv.BORDER_DEFAULT);
    cv.GaussianBlur(grayB, blurB, ksize, 0, 0, cv.BORDER_DEFAULT);

    let diff = new cv.Mat();
    cv.absdiff(blurA, blurB, diff);
    let magnitude = new cv.Mat();
    diff.convertTo(magnitude, cv.CV_32F);
    blurA.delete();
    blurB.delete();
    diff.delete();
    return { magnitude: magnitude, angle: null };
  } else {
    let flow = new cv.Mat();
    cv.calcOpticalFlowFarneback(grayA, grayB, flow, 0.5, levels, windowSize, 3, 5, 1.2, 0);
    let flowChannels = new cv.MatVector();
    cv.split(flow, flowChannels);
    let flowX = flowChannels.get(0);
    let flowY = flowChannels.get(1);
    let magnitude = new cv.Mat();
    let angle = new cv.Mat();
    cv.cartToPolar(flowX, flowY, magnitude, angle, true);
    flowX.delete();
    flowY.delete();
    flowChannels.delete();
    flow.delete();
    return { magnitude: magnitude, angle: angle };
  }
}

// Renders flow/CFS magnitude for the full frame onto the main output canvas.
// Takes magnitude + angle directly (angle is null for CFS — no direction).
function visualizeFlow(magnitude, angle) {
  let magNorm = new cv.Mat();
  normalizeMagnitudeRobust(magnitude, magNorm);
  applyGammaCorrection(magNorm);

  // HSV mode needs direction (angle) to make sense. CFS has none, so fall
  // back to grayscale instead of showing a meaningless/undefined hue.
  let effectiveColorMode = (colorMode === 'hsv' && angle == null) ? 'grayscale' : colorMode;

  if (effectiveColorMode === 'hsv') {
    // Direction (angle) -> hue, magnitude -> value. Only mode that encodes flow direction.
    let hsv = new cv.Mat();
    let hsvChannels = new cv.MatVector();
    let sat = new cv.Mat(magnitude.rows, magnitude.cols, cv.CV_32F, new cv.Scalar(255));
    hsvChannels.push_back(angle);
    hsvChannels.push_back(sat);
    hsvChannels.push_back(magNorm);
    cv.merge(hsvChannels, hsv);

    let hsv8 = new cv.Mat();
    hsv.convertTo(hsv8, cv.CV_8U);
    let outputImg = new cv.Mat();
    cv.cvtColor(hsv8, outputImg, cv.COLOR_HSV2RGB);
    cv.imshow('output', outputImg);
    outputImg.delete();

    hsv8.delete();
    hsv.delete();
    sat.delete();
    hsvChannels.delete();
  } else if (effectiveColorMode === 'grayscale') {
    let outputImg = toGray8(magNorm);
    cv.imshow('output', outputImg);
    outputImg.delete();
  } else {
    // viridis / magma — pure JS/Canvas path, no OpenCV colormap functions
    let gray8 = toGray8(magNorm);
    renderMagnitudeColormap(gray8, ctx, 0, 0);
    gray8.delete();
  }

  magNorm.delete();
}

// Renders flow/CFS magnitude only within the selected ROI, drawn onto the
// canvas at the ROI's position. Must live at the top level (NOT nested
// inside visualizeFlow) so captureFrames() can actually call it.
function visualizeFlowInROI(magnitude, angle, roi) {
  let magNorm = new cv.Mat();
  normalizeMagnitudeRobust(magnitude, magNorm);
  applyGammaCorrection(magNorm);

  let effectiveColorMode = (colorMode === 'hsv' && angle == null) ? 'grayscale' : colorMode;

  let tempCanvas = document.createElement('canvas');
  tempCanvas.width = Math.floor(roi.w);
  tempCanvas.height = Math.floor(roi.h);
  let tempCtx = tempCanvas.getContext('2d');

  if (effectiveColorMode === 'hsv') {
    let hsv = new cv.Mat();
    let hsvChannels = new cv.MatVector();
    let sat = new cv.Mat(magnitude.rows, magnitude.cols, cv.CV_32F, new cv.Scalar(255));
    hsvChannels.push_back(angle);
    hsvChannels.push_back(sat);
    hsvChannels.push_back(magNorm);
    cv.merge(hsvChannels, hsv);
    let hsv8 = new cv.Mat();
    hsv.convertTo(hsv8, cv.CV_8U);
    let outputMat = new cv.Mat();
    cv.cvtColor(hsv8, outputMat, cv.COLOR_HSV2RGB);
    cv.imshow(tempCanvas, outputMat);
    outputMat.delete();
    hsv8.delete();
    hsv.delete();
    sat.delete();
    hsvChannels.delete();
  } else if (effectiveColorMode === 'grayscale') {
    let outputMat = toGray8(magNorm);
    cv.imshow(tempCanvas, outputMat);
    outputMat.delete();
  } else {
    let gray8 = toGray8(magNorm);
    renderMagnitudeColormap(gray8, tempCtx, 0, 0);
    gray8.delete();
  }

  ctx.drawImage(tempCanvas, Math.floor(roi.x), Math.floor(roi.y));

  magNorm.delete();
}
